variables:
  S3CFG: "/root/.s3cfg"

stages:
    - build
    - publish

default:
    # Only the build stage actually requires a `virt` tagged runner, the rest can use `docker`
    tags:
        - docker

include:
    - local: template_build.yml
      inputs:
        template_name: almalinux-8
    - local: template_build.yml
      inputs:
        template_name: almalinux-9
    - local: template_build.yml
      inputs:
        template_name: almalinux-10
    - local: template_build.yml
      inputs:
        template_name: cloudlinux-8
    - local: template_build.yml
      inputs:
        template_name: cloudlinux-9
    - local: template_build.yml
      inputs:
        template_name: debian-11
    - local: template_build.yml
      inputs:
        template_name: debian-12
    - local: template_build.yml
      inputs:
        template_name: ubuntu-22.04
    - local: template_build.yml
      inputs:
        template_name: ubuntu-24.04
